# Generated by Django 2.2.28 on 2023-06-09 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_characteristics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characteristics',
            name='pet',
        ),
    ]
